language: python
python:
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - cd deptos
  - python manage.py migrate 

# command to run tests
script:
- python manage.py test 
